import {
  Wallet,
  Banknote,
  TrendingUp,
  Gift,
  RefreshCcw,
  Briefcase,
  CircleDollarSign,
  ShoppingBag,
  Utensils,
  Home,
  Plug,
  Car,
  HeartPulse,
  ShieldCheck,
  GraduationCap,
  AlertTriangle,
  Film,
  ShoppingCart,
  Plane,
  Sparkles,
  Dumbbell,
  Repeat,
  Dog,
  Users,
  Receipt,
  Landmark,
  CreditCard,
  PiggyBank,
  ChartBar,
  Handshake,
  CircleHelp,
  ArrowUpRight,
  ArrowDownLeft,
} from "lucide-react";

// Map MongoDB string values to Lucide Components
export const ICON_MAP = {
  Wallet,
  Banknote,
  TrendingUp,
  Gift,
  RefreshCcw,
  Briefcase,
  CircleDollarSign,
  ShoppingBag,
  Utensils,
  Home,
  Plug,
  Car,
  HeartPulse,
  ShieldCheck,
  GraduationCap,
  AlertTriangle,
  Film,
  ShoppingCart,
  Plane,
  Sparkles,
  Dumbbell,
  Repeat,
  Dog,
  Users,
  Receipt,
  Landmark,
  CreditCard,
  PiggyBank,
  ChartBar,
  Handshake,
  CircleHelp,
  ArrowUpRight,
  ArrowDownLeft,
};

export const CATEGORY_COLORS = {
  // Income
  Salary: "#10B981",
  Freelance: "#059669",
  "Business Income": "#3B82F6",
  "Investments Income": "#8B5CF6",
  "Gifts Received": "#EC4899",
  Refunds: "#6366F1",
  "Other Income": "#64748B",

  // Expenses
  Groceries: "#F59E0B",
  "Food & Dining": "#F97316",
  Housing: "#3B82F6",
  Rent: "#3B82F6",
  Utilities: "#0EA5E9",
  Transportation: "#EF4444",
  Healthcare: "#F43F5E",
  Insurance: "#0D9488",
  Education: "#8B5CF6",
  Emergency: "#DC2626",
  Entertainment: "#EC4899",
  Shopping: "#D946EF",
  Travel: "#06B6D4",
  "Personal Care": "#FEF08A",
  Fitness: "#84CC16",
  Subscriptions: "#6366F1",
  Pets: "#A855F7",
  "Family & Kids": "#FB7185",
  Bills: "#64748B",
  "Loan EMI": "#94A3B8",
  "Credit Card Payment": "#F43F5E",
  Savings: "#10B981",
  Investments: "#14B8A6",
  Charity: "#F59E0B",
  Miscellaneous: "#9CA3AF",
};

// Helper to auto-select icon based on category name
export const getIconForCategory = (category) => {
  const map = {
    Salary: "Wallet",
    Freelance: "Banknote",
    "Business Income": "Briefcase",
    "Investments Income": "TrendingUp",
    "Gifts Received": "Gift",
    Refunds: "RefreshCcw",
    "Other Income": "CircleDollarSign",
    Groceries: "ShoppingBag",
    "Food & Dining": "Utensils",
    Housing: "Home",
    Rent: "Home",
    Utilities: "Plug",
    Transportation: "Car",
    Healthcare: "HeartPulse",
    Insurance: "ShieldCheck",
    Education: "GraduationCap",
    Emergency: "AlertTriangle",
    Entertainment: "Film",
    Shopping: "ShoppingCart",
    Travel: "Plane",
    "Personal Care": "Sparkles",
    Fitness: "Dumbbell",
    Subscriptions: "Repeat",
    Pets: "Dog",
    "Family & Kids": "Users",
    Bills: "Receipt",
    "Loan EMI": "Landmark",
    "Credit Card Payment": "CreditCard",
    Savings: "PiggyBank",
    Investments: "ChartBar",
    Charity: "Handshake",
    Miscellaneous: "CircleHelp",
  };
  return map[category] || "CircleHelp";
};